#### get all category

GET http://0.0.0.0:8080/v1/categories
Accept: application/json

#### get 1 by id

GET http://0.0.0.0:8080/v1/categories?id=2
Accept: application/json

#### create new

POST http://0.0.0.0:8080/v1/categories/create
Content-Type: application/json

{
  "name": "pokemon"
}

#### update items

POST http://0.0.0.0:8080/v1/categories/update
Content-Type: application/json

{
  "categoryId" : -226491478483879878,
  "name": "New Product 2"
}

#### remove

POST http://0.0.0.0:8080/v1/categories/remove
Content-Type: application/json

{
  "categoryId" : 3562498663721392472
}